services:
    smartcookies_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smartcookies_app
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - smartcookies_db
    smartcookies_db:
        image: mysql:8.0
        container_name: smartcookies_db
        environment:
            MYSQL_DATABASE: smartcookies_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app_user
            MYSQL_PASSWORD: password
        volumes:
          - smartcookies_db_data:/var/lib/mysql
          - ./docker/mysql/init-legacy.sh:/docker-entrypoint-initdb.d/init-legacy.sh:ro
          - ./dump.sql:/tmp/dump.sql:ro
        ports:
            - "33066:3306"

volumes:
    smartcookies_db_data:
