name: Deploy SmartCookie

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Форсируем использование Node 24 для всех экшенов
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/smartcookie
            # Сброс локальных изменений, чтобы git pull не падал
            git fetch origin main
            git reset --hard origin/main
            
            # Обновление проекта
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            
            # Оптимизация кэша
            php artisan optimize
